# 00. PyTorch fundamentals
- Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
- Discussions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
# importing modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import torch
# printing torch version
print(torch.__version__)

1.13.0+cu116


## Introduction to Tensors
### Creation 

In [ ]:
# tensors are multi-dimentional matrices containing elements of a single data type
# like a numpy array
# scalar
scalar = torch.tensor(7) 
scalar

tensor(7)

In [ ]:
# number of dimensions
scalar.ndim # 0 because it has no dimensions
# to retrieve the scalar tensor as a scalar 
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# vectors have only 1 dimension (number of square brackets)
vector.ndim 

1

In [ ]:
# shape : number of elements of the tensor in each dim
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,5], [6,3]])
MATRIX

tensor([[7, 5],
        [6, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR =torch.tensor([[[1]]])
TENSOR

tensor([[[1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1])

**Remark:** Tensors and Matrices variables are in uppercase as for scalars and vectors are lower case. 

## Random tensors
### Why random tensors?
 Many neural networks are initialized by a random tensor, then updated throughout the process

In [ ]:
# Creation a rand tensor of size (3, 4)
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.2501, 0.4213, 0.3623, 0.6472],
        [0.0009, 0.2274, 0.5586, 0.0813],
        [0.0742, 0.1952, 0.6939, 0.6048]])

In [ ]:
# sometimes, we have to deal with images
# here is to generate a random image
rand_tensor_image_shape = torch.rand(size=(3, 224, 224))  # color_channels (R,G,B), height, width
rand_tensor_image_shape

tensor([[[0.4403, 0.7950, 0.7798,  ..., 0.1825, 0.8168, 0.2645],
         [0.2597, 0.7358, 0.5136,  ..., 0.4352, 0.5525, 0.7705],
         [0.2535, 0.3292, 0.9177,  ..., 0.4788, 0.6459, 0.3621],
         ...,
         [0.4044, 0.9029, 0.5321,  ..., 0.2035, 0.5110, 0.0797],
         [0.0861, 0.1604, 0.5727,  ..., 0.8903, 0.2978, 0.7776],
         [0.9493, 0.4539, 0.5486,  ..., 0.4111, 0.2850, 0.4534]],

        [[0.8725, 0.0279, 0.3331,  ..., 0.4392, 0.1142, 0.9882],
         [0.3311, 0.3775, 0.3633,  ..., 0.0598, 0.8371, 0.2277],
         [0.2752, 0.3730, 0.8148,  ..., 0.1052, 0.4814, 0.3400],
         ...,
         [0.2368, 0.7888, 0.2790,  ..., 0.4079, 0.3628, 0.0393],
         [0.6532, 0.2960, 0.3810,  ..., 0.9677, 0.0309, 0.8478],
         [0.2482, 0.7778, 0.7803,  ..., 0.9832, 0.4347, 0.5290]],

        [[0.0234, 0.1972, 0.6300,  ..., 0.4546, 0.6508, 0.5003],
         [0.9366, 0.3343, 0.3750,  ..., 0.2875, 0.2597, 0.8751],
         [0.7578, 0.8630, 0.1698,  ..., 0.9339, 0.7287, 0.

##  Zeroes and ones
Generally, useful when we are creating masks 

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size= (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# dtype -> the type of the data stored in the tensor

## Range and tensors-like

In [ ]:
# tensor arange
one_to_five = torch.arange(start=1, end=6, step=1)
one_to_five
# end is not included

tensor([1, 2, 3, 4, 5])

In [ ]:
# Creating tensors like
five_zeros = torch.zeros_like(one_to_five)
five_zeros
five_ones = torch.ones_like(one_to_five)
five_ones

tensor([1, 1, 1, 1, 1])

## Tensor datatypes
- The default datatype for torch tensors is float32

In [ ]:
# Float 32 tensors
# we usually use float 32 or float 16, the 32 and 16 is related to the precision
# of the float numbers we are dealing with
# if dtype is fixed to None, then by default float32
tensor_32 = torch.tensor([1,2,3],
                         dtype=torch.float32,
                         device=None, # cpu or cuda (gpu)
                         requires_grad=False)
tensor_32
# we can't do numerical calculations between tensors which aren't in the same 
#device

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# we can convert tensorts from one type to another one
float_16_tensor = tensor_32.type(torch.int16)
float_16_tensor

tensor([1, 2, 3], dtype=torch.int16)

In [ ]:
float_16_tensor * tensor_32

tensor([1, 4, 9], dtype=torch.int32)

In [ ]:
## we can't let requires_grad = True for int tensors

### Getting informations from the tensors
1. Tensors not right datatype, `tensor.dtype`
2. Tensors not right shape, `tensor.shape`
3. Tensors not right device, `tensor.device`

In [ ]:
# example
tensor_ex = torch.rand(size=(3, 4))
print(f" - Datatype: {tensor_ex.dtype} \n - Shape: {tensor_ex.shape} \n - Device: {tensor_ex.device}")

 - Datatype: torch.float32 
 - Shape: torch.Size([3, 4]) 
 - Device: cpu


## Manipulating Tensors
Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# example
t1 = torch.tensor([1,2,3])
# adding 10
t1 + 10

tensor([11, 12, 13])

In [ ]:
# multiplying by 10
t1 * 10

tensor([10, 20, 30])

In [ ]:
# substracting 10
t1 - 10

tensor([-9, -8, -7])

In [ ]:
# dividing by 10
t1 / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# to the power of 2
t1 ** 2

tensor([1, 4, 9])

In [ ]:
# element-wise multiplication
t1 * t1

tensor([1, 4, 9])

## Matrix Multiplication "dot product"


In [ ]:
# Example
# scalar product of two vectors
torch.matmul(t1, t1)

tensor(14)

In [ ]:
X = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([1,2])
# matrix * vector
torch.matmul(X, y) 
# matrix * matrix
torch.mm(X, X) # torch.mm is the same as torch.matmul 

tensor([[ 7, 10],
        [15, 22]])

 One of the major problems when doing multiplications is those related to the shapes,
 we are handling. There are several methods to correct the shape of our tensors:
 1. Transposing
 2. Reshaping

In [ ]:
# Transposing a matrix
Z = X.mT
Z

tensor([[1, 3],
        [2, 4]])

## Finding the min, max, sum, mean, etc " Tensor Aggregation"

In [ ]:
# create a tensor
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# find the max
x.max()

tensor(9)

In [ ]:
# find the min
x.min()

tensor(1)

In [ ]:
# find the mean 
# mean function cannot return an integer, we should specify it
x.mean(dtype = torch.float32)
# another way to do it
x.type(torch.float32).mean()
# we can also use it torch.mean(x.type(torch.float32))

tensor(5.)

In [ ]:
x.sum()

tensor(45)

## Finding the positional min and max

In [ ]:
# find the position of the min/max value and returns its index
x.argmin()
x.argmax()

tensor(8)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same momory as the origibnal tensor
* Stacking - combine multiple tensors on top of each other (vstack), of side by side (vstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimention to a target torch
* Permute - returns a view of the input in dimensions permuted in a certain manner

In [ ]:
# Example
# creating a tensor
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# reshape
x_reshaped = x.reshape(3, 3) # this should compatible with the dimensions
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# change the view
z = x.view(1, 9)
z
# view works just like reshape however since they share the same memory if we modify one of them, 
#the other one is modified as wel

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Stack tensors on top of each others
x = torch.arange(1,3)
y = torch.vstack((x,x))
# another way, y = torch.stack((x,x), dim = 0)
y

tensor([[1, 2],
        [1, 2]])

In [ ]:
# Stack side by side (dim = 1)
y = torch.hstack((x, x))
y

tensor([1, 2, 1, 2])

In [ ]:
# Squeeze & Unsqueeze
y = y.unsqueeze(dim = 1)
y.squeeze()

tensor([1, 2, 1, 2])

In [ ]:
# permute
x = torch.rand(2,3,5)
y = torch.permute(x, dims = (2,1,0))
# y is only a view of x, so changing one of them will change the other
x.shape, y.shape

(torch.Size([2, 3, 5]), torch.Size([5, 3, 2]))

In [ ]:
x,y

(tensor([[[0.3448, 0.9528, 0.8805, 0.7942, 0.8993],
          [0.8234, 0.0051, 0.0115, 0.9791, 0.4570],
          [0.8876, 0.5111, 0.2628, 0.7321, 0.1537]],
 
         [[0.0213, 0.1229, 0.3649, 0.5652, 0.1025],
          [0.0162, 0.0993, 0.6043, 0.6749, 0.1357],
          [0.3781, 0.5556, 0.9130, 0.6208, 0.1848]]]),
 tensor([[[0.3448, 0.0213],
          [0.8234, 0.0162],
          [0.8876, 0.3781]],
 
         [[0.9528, 0.1229],
          [0.0051, 0.0993],
          [0.5111, 0.5556]],
 
         [[0.8805, 0.3649],
          [0.0115, 0.6043],
          [0.2628, 0.9130]],
 
         [[0.7942, 0.5652],
          [0.9791, 0.6749],
          [0.7321, 0.6208]],
 
         [[0.8993, 0.1025],
          [0.4570, 0.1357],
          [0.1537, 0.1848]]]))

In [ ]:
x[0][0][0] = 1000

In [ ]:
y

tensor([[[1.0000e+03, 2.1328e-02],
         [8.2342e-01, 1.6234e-02],
         [8.8760e-01, 3.7812e-01]],

        [[9.5275e-01, 1.2294e-01],
         [5.1159e-03, 9.9292e-02],
         [5.1112e-01, 5.5562e-01]],

        [[8.8049e-01, 3.6493e-01],
         [1.1511e-02, 6.0430e-01],
         [2.6284e-01, 9.1296e-01]],

        [[7.9424e-01, 5.6516e-01],
         [9.7912e-01, 6.7485e-01],
         [7.3214e-01, 6.2085e-01]],

        [[8.9928e-01, 1.0251e-01],
         [4.5697e-01, 1.3572e-01],
         [1.5369e-01, 1.8485e-01]]])

## Selecting data from tensors "Indexing"
It is quite similar to indexing in NumPy.

In [ ]:
# let's do it
x = torch.arange(9).reshape(1,3,3)
x

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
x[0]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
x[0,0]

tensor([0, 1, 2])

In [ ]:
x[0,[0,2],[1]]

tensor([1, 7])

In [ ]:
x[0,:,2]

tensor([2, 5, 8])

In [ ]:
x[:,:,1]

tensor([[1, 4, 7]])

In [ ]:
x[:,1,1]

tensor([4])

In [ ]:
x[0,2,2]

tensor(8)

In [ ]:
x[0,:,2]

tensor([2, 5, 8])

## Pytorch and NumPy
* NumPy -> Torch : `torch.from_numpy()`
* Torch -> NumPy: `.numpy()`

In [ ]:
import numpy as np
a = np.linspace(0,10)
tensor = torch.from_numpy(a)  # warning: by default numpy dtype is float64
tensor

tensor([ 0.0000,  0.2041,  0.4082,  0.6122,  0.8163,  1.0204,  1.2245,  1.4286,
         1.6327,  1.8367,  2.0408,  2.2449,  2.4490,  2.6531,  2.8571,  3.0612,
         3.2653,  3.4694,  3.6735,  3.8776,  4.0816,  4.2857,  4.4898,  4.6939,
         4.8980,  5.1020,  5.3061,  5.5102,  5.7143,  5.9184,  6.1224,  6.3265,
         6.5306,  6.7347,  6.9388,  7.1429,  7.3469,  7.5510,  7.7551,  7.9592,
         8.1633,  8.3673,  8.5714,  8.7755,  8.9796,  9.1837,  9.3878,  9.5918,
         9.7959, 10.0000], dtype=torch.float64)

In [ ]:
num_array = (tensor + 10).numpy()
num_array[0] = 78
num_array, tensor
# they are stocked in two different locations in memory, thus chnaging one of them won't affect the other one

(array([78.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
        11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
        12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
        13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
        14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
        15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
        16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
        17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
        18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
        19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ]),
 tensor([ 0.0000,  0.2041,  0.4082,  0.6122,  0.8163,  1.0204,  1.2245,  1.4286,
          1.6327,  1.8367,  2.0408,  2.2449,  2.4490,  2.6531,  2.8571,  3.0612,
          3.2653,  3.4694,  3.6735,  3.8776,  4.0816,  4.2857,  4.4898,  4.6939,
          4.8980,  5.1020

## Reproducibility
Briefly, a neural network learn as follows:
`start with random numbers -> tensor operations -> updating parameters -> again ...` 
To reduce the randomness in neural networks and PyTorch, we have to fix the seed.

In [ ]:
# setting random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [ ]:
a = torch.rand(1,2)
torch.manual_seed(RANDOM_SEED)
b = torch.rand(1, 2)
a == b

tensor([[True, True]])

## Accessing the GPU

### 1. Getting a GPU
 - Using Google Colab
 - Using your own gpu
 - Use cloud computing like AWS, Azure, ...

### 2. Checking for GPU acces using Pytorch

In [ ]:
# checking for gpu access
torch.cuda.is_available()

False

In [ ]:
# setup device agnostic code
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

In [ ]:
device

'cpu'

### 3. Best practise

Check the link: https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

In [ ]:
# converting tensors to device
tensor_con = tensor.to(device)

In [ ]:
# if a tensor is in gpu we can't convert it to numpy array
num_arr = tensor_con.cpu().numpy()

## Exercices

In [ ]:
import torch
# seeting seed to 0
torch.manual_seed(1234)
# creating a random tensor
tensor_rand = torch.rand(7,7)
# tensors multiplication
tensor_2 = torch.rand(1,7)
torch.mm(tensor_rand, tensor_2.mT)
# when using a gpu
torch.cuda.manual_seed(1234)
# if we are using several gpus
torch.cuda.manual_seed_all(1234)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tens1 = torch.rand(2,3).to(device)
tens2 = torch.rand(2, 3).to(device)
X= torch.mm(tens1, tens2.mT)
min, max = X.min(), X.max()
argmi, argma = X.argmin(), X.argmax()
print(min, max, argmi, argma)
new_tens = torch.rand(1, 1, 1, 10)
torch.manual_seed(7)
squeezed = new_tens.squeeze()
print(new_tens,squeezed)
print(new_tens.shape, squeezed.shape)

tensor(0.2573, device='cuda:0') tensor(0.8202, device='cuda:0') tensor(0, device='cuda:0') tensor(3, device='cuda:0')
tensor([[[[0.2908, 0.4196, 0.3728, 0.3769, 0.0108, 0.9455, 0.7661, 0.2634,
           0.1880, 0.5174]]]]) tensor([0.2908, 0.4196, 0.3728, 0.3769, 0.0108, 0.9455, 0.7661, 0.2634, 0.1880,
        0.5174])
torch.Size([1, 1, 1, 10]) torch.Size([10])


## Extra-curriculum

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html